version: '3.5'

services:
  udmurtapi:
    build: .
    container_name: udmapi
    # command: ls && uvicorn app.main:app --host 0.0.0.0 --port 2180
    command: bash bootstrap.sh && uvicorn app.main:app --host 0.0.0.0 --port 2180
    volumes:
      - ./images:/code/images
      - ./data:/code/data
    ports:
      - "2180:2180"